---

title: How do I

body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: |
        Ask your question in as much detail as you like.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context of the question
      description: >-
        This field is optional. It helps if you provide additional context for your question, thus helping us better
        understand what you are working on and what you are trying to achieve.
    validations:
      required: false

  - type: textarea
    id: example-code
    description: >-
      This field is optional. If you have some code or configuration that you want so share here is a good place.
      Markdown fenced codeblocks go a long way for readability.
    attributes:
      label: Example Code
      value: |
        ```console
        $
        ```

        Configuration

        ```yaml

        ```
    validations:
      required: false
  - type: textarea
    id: reference
    attributes:
      label: Reference
      value: |
        *
    validations:
      required: false

...
