---

name: 📚 Documentation
description: Request for changes in documentation
title: "[Documentation]: "
labels:
  - documentation 📚
assignees:
  - maintainers
body:

  - type: markdown
    attributes:
      value: >-
        :tada: :tada: Thank you for taking the time to request a documentation improvement :tada: :tada:

  - type: markdown
    attributes:
      value: |
        This template is strictly used for documentation requests, including:

        - Elaborating on a particular topic;
        - Updating external links;
        - Anything else that doesn't require touching the codebase itself.

        If you followed the documentation but things don't work, take some time to consider if it's the documentation or the code that's wrong. In the latter, prefer using the "bug" template.

        You may proceed directly to sending a pull request without filing this issue, and we can improve your work. If you think some of the requirements above are not met, or if you are not able to contribute yourself, the issue is still welcomed.

  - type: textarea
    id: request-info
    attributes:
      label: Description
      description: >-
        Tell us, what can be done better or a clear and concise description of what the issue is.
    validations:
      required: true

  - type: dropdown
    id: ecosystem
    attributes:
      label: Select the area that is associated with this issue.
      multiple: true
      options:
        - Instructions
        - Examples
        - Module
        - Other

  - type: checkboxes
    attributes:
      label: Self-service
      description: >-
        If want to contribute to this issue, please check the box below. This let tell us and other people looking for contributions know that someone's working on it.
        If you check this box, please send a pull request within 7 days so we do not delegate this issue to someone else.
      options:
        - label: >-
            I will address this request myself.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description: >-
        Please ensure your request fulfills all of the following requirements. If you are not sure what a specific
        requirement means, follow the link to learn more and understand why it is necessary before ticking the boxes.
        This will save maintainers and you valuable time.
      options:
        - label: >-
            I have read the [Contributing Guidelines](../blob/main/CONTRIBUTING.md).
          required: true
        - label: >-
            I agree to follow the Mantoso [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md)
          required: true

...
